# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from menu2 import *

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CT(object):
    def submit(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_menu_stage()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, CT):
        CT.setObjectName("CT")
        CT.resize(300, 386)
        CT.setMinimumSize(QtCore.QSize(300, 300))
        CT.setMaximumSize(QtCore.QSize(300, 500))
        CT.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(CT)
        self.centralwidget.setObjectName("centralwidget")
        self.heading = QtWidgets.QLabel(self.centralwidget)
        self.heading.setGeometry(QtCore.QRect(90, 0, 91, 41))
        self.heading.setObjectName("heading")
        self.label_summary = QtWidgets.QLabel(self.centralwidget)
        self.label_summary.setGeometry(QtCore.QRect(60, 190, 181, 121))
        self.label_summary.setText("")
        self.label_summary.setWordWrap(True)
        self.label_summary.setObjectName("label_summary")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.submit())
        self.pushButton.setGeometry(QtCore.QRect(110, 150, 56, 17))
        self.pushButton.setObjectName("pushButton")
        CT.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CT)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 18))
        self.menubar.setObjectName("menubar")
        CT.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CT)
        self.statusbar.setObjectName("statusbar")
        CT.setStatusBar(self.statusbar)

        self.retranslateUi(CT)
        QtCore.QMetaObject.connectSlotsByName(CT)

    def retranslateUi(self, CT):
        _translate = QtCore.QCoreApplication.translate
        CT.setWindowTitle(_translate("CT", "Test 10"))
        self.heading.setText(_translate("CT", "BILL CALCULATOR"))
        self.pushButton.setText(_translate("CT", "MENU"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CT = QtWidgets.QMainWindow()
    ui = Ui_CT()
    ui.setupUi(CT)
    CT.show()
    sys.exit(app.exec_())
